name: "Build"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: lopsided98/nix-ros-build-action@master
      with:
        cachix-signing-key: '${{ secrets.CACHIX_SIGNING_KEY }}'
